language: python
python:
  - "3.7"
os: linux
dist: bionic
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - flake8 .
  - pytest
  - python tests/integration.py
# only build master and develop
branches:
  only:
  - master
  - develop