language: python
python:
  - "3.7"
os: linux
dist: bionic
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
before_script:
  - mkdir /home/travis/.behavenet/
  - echo '{"data_dir": "/home/travis/data", "save_dir": "/home/travis/save", "fig_dir": "home/travis/figs"}' > /home/travis/.behavenet/directories.json
# command to run tests
script:
  - flake8 .
  - pytest
  - python tests/integration.py
# only build master and develop
branches:
  only:
  - master
  - develop